# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16GmvH4pphuSxv5wQ2tBS8coMvEN1D_11

# Proyek Akhir: Menyelesaikan Permasalahan Perusahaan Edutech

- Nama: Juniyara Parisya Setiawan
- Email: parissajuniara@gmail.com
- Id Dicoding: juniyaraparisya

## Persiapan

### Menyiapkan library yang dibutuhkan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE
from sklearn.impute import SimpleImputer

from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix
from xgboost import XGBClassifier


import joblib

"""### Menyiapkan data yang akan diguankan"""

df = pd.read_csv('https://raw.githubusercontent.com/dicodingacademy/dicoding_dataset/refs/heads/main/employee/employee_data.csv')

"""## Data Understanding"""

df.info()

df.head(5)

df.isna().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)
df.duplicated().sum()

"""Tidak ada duplikat dalam data sehingga dapat dilakukan langkah selanjutnya."""

df['Attrition'].fillna(2, inplace=True)
df['Attrition'] = df['Attrition'].astype(int)
df['Attrition'].value_counts()

df.isnull().sum()

df.nunique()

df.drop((['Over18', 'StandardHours', 'EmployeeCount']), axis = 1, inplace=True)

"""penghapusan data dilakukan karena tidak memiliki data yang berbeda atau unik, sehingga data tidak dapat mendapatkan pola untuk analisis."""

df.info()

df.describe()

df['Attrition'].value_counts(normalize=True)

# Perbandingan data

num_feature = df[df['Attrition'] != 2].groupby('Attrition').mean(numeric_only = True)
Data_perbandingan = num_feature.T

plt.figure(figsize=(12, 10))
sns.heatmap(Data_perbandingan, annot = True, cmap='viridis', fmt='.2f',linewidths = 5, linecolor='black')

# First, ensure 'comparison_data' correctly contains only the mean of numeric features.
# Filter out Attrition = 2 (NaN values) for comparison between 0 and 1
comparison_data = df[df['Attrition'] != 2].groupby('Attrition').mean(numeric_only=True)

# We will transpose it so that features are rows and Attrition categories are columns for easier visualization.
heatmap_data_for_comparison = comparison_data.T

plt.figure(figsize=(12, 10))
sns.heatmap(heatmap_data_for_comparison, annot=True, cmap='viridis', fmt='.2f', linewidths=.5, linecolor='black')
plt.title('Rata-rata Fitur Numerik berdasarkan Status Attrition', fontsize=16)
plt.xlabel('Status Attrition')
plt.ylabel('Fitur Numerik')
plt.xticks(ticks=[0.5, 1.5], labels=['Tidak Mengundurkan Diri (0)', 'Mengundurkan Diri (1)'], rotation=0)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

corr = df.corr(numeric_only = True)
plt.figure(figsize=(10, 10))
sns.heatmap(data=corr, annot=True, cmap='coolwarm', linewidths=0.5, fmt = ".2f")
plt.title(" Correlation Matrix Between Numerical Feature", size = 20)
plt.show()

"""dapat dilihat terdapat bola pada correlation matrix dimana korelasi diatas 0.7 merupakat pola untuk feature pada model, dimana pola yang dapat digunakan adalah
* ***PerformanceRating*** dengan ***PercentSalaryHike***,
* **JobLevel** dengan **TotalWorkingYears**
* **Joblevel** dengan **MontlyIncome**
* **YearsAtCompany** dengan **YearsInCurrentRole**
* **YearsAtCompany** dengan **YearsWitchCurrManager**
* **YearsInCurrentRole** dengan **YearsWitchCurrManager**

"""

# Korelasi Attrion dengan Fitur Numerics

numerical_features = df.select_dtypes(include=np.number).columns
corr_matrix = df[numerical_features].corr().abs()
corr_attrion = corr_matrix['Attrition'].sort_values(ascending=False)
corr_attrion

df.info()

"""## Data Preparation / Preprocessing"""

median_attrition = df['Attrition'].median()
df['Attrition'].replace(2, median_attrition, inplace=True)

df['Attrition'] = df['Attrition'].astype(int)

print(df['Attrition'].value_counts())

df.head()

X = df.drop('Attrition', axis=1)
y = df['Attrition']

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=42,
                                                    stratify=y)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

numerical_cols = ['Education', 'EnvironmentSatisfaction', 'JobInvolvement', 'JobLevel',
                  'JobSatisfaction', 'NumCompaniesWorked', 'PercentSalaryHike',
                  'RelationshipSatisfaction', 'StockOptionLevel', 'TrainingTimesLastYear',
                  'WorkLifeBalance', 'YearsSinceLastPromotion',
                  'Age', 'DailyRate', 'DistanceFromHome', 'HourlyRate', 'MonthlyIncome', 'MonthlyRate', 'TotalWorkingYears', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager'
                  ]

categorical_cols = ['BusinessTravel', 'Department', 'EducationField', 'Gender',
                    'JobRole', 'MaritalStatus', 'OverTime']

numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ]
)

"""## Modeling"""

X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_processed, y_train)

xgb_model = Pipeline(steps=[
    ('classifier', XGBClassifier())
])

param_space_xgb = {
    'classifier__n_estimators': [10, 20 ,50, 100],
    'classifier__max_depth': [3, 5, 7, 10],
    'classifier__gamma': [0.01, 0.1, 0.2, 0.3]
}

model_xgb = GridSearchCV(xgb_model, param_grid=param_space_xgb, cv=5)

model_xgb.fit(X_train_resampled, y_train_resampled)

print("Best Parameters:", model_xgb.best_params_)
print("Training Accuracy:", model_xgb.score(X_train_resampled, y_train_resampled))
print("Model Best Score (XGBoost):", model_xgb.best_score_)
print("Test Accuracy:", model_xgb.score(X_test_processed, y_test))

"""## Evaluation"""

y_pred_xgb = model_xgb.predict(X_test_processed)

print("\nConfusion Matrix XGBoost:")
print(confusion_matrix(y_test, y_pred_xgb))

print("\nClassification Report XGBoost:")
print(classification_report(y_test, y_pred_xgb))

y_pred_xgb = model_xgb.predict(X_test_processed)

print("\nConfusion Matrix XGBoost:")
print(confusion_matrix(y_test, y_pred_xgb))

print("\nClassification Report XGBoost:")
print(classification_report(y_test, y_pred_xgb))

df['Attrition'] = df['Attrition'].replace({0: 'Tidak Mengundurkan Diri',
                                           1: 'Mengundurkan Diri',
                                           2: 'tTidak Diketakui'})
display(df['Attrition'].head())

joblib.dump(preprocessor, 'preprocessor.pkl')
joblib.dump(model_xgb, 'xgboost_model.pkl')